services:
  owntone:
    image: docker.io/owntone/owntone:latest
    container_name: turntable-owntone
    network_mode: host
    environment:
      UID: "${OWNTONE_UID:-1000}"
      GID: "${OWNTONE_GID:-100}"
    volumes:
      - ${TURNTABLE_HOST_PATH:-/srv/dev-disk-by-uuid-ed0cc40b-12e9-481a-9c82-203c8a67d732/turntable}/owntone/etc:/etc/owntone
      - ${TURNTABLE_HOST_PATH:-/srv/dev-disk-by-uuid-ed0cc40b-12e9-481a-9c82-203c8a67d732/turntable}/owntone/media:/srv/media
      - ${TURNTABLE_HOST_PATH:-/srv/dev-disk-by-uuid-ed0cc40b-12e9-481a-9c82-203c8a67d732/turntable}/owntone/cache:/var/cache/owntone
    restart: unless-stopped
