#!/bin/sh
set -eu

: "${ALSA_CAPTURE_DEVICE:=hw:CARD=CODEC,DEV=0}"
: "${ALSA_CAPTURE_CHANNELS:=2}"
: "${ALSA_CAPTURE_RATE:=44100}"
: "${ALSA_CAPTURE_PERIOD_SIZE:=256}"
: "${ALSA_CAPTURE_BUFFER_SIZE:=2048}"
export ALSA_CAPTURE_DEVICE ALSA_CAPTURE_CHANNELS ALSA_CAPTURE_RATE
export ALSA_CAPTURE_PERIOD_SIZE ALSA_CAPTURE_BUFFER_SIZE

envsubst < /etc/asound.conf.template > /etc/asound.conf
exec "$@"
