alias: Plattenspieler OwnTone starten
mode: restart
trigger:
  - platform: state
    entity_id: binary_sensor.plattenspieler_aktiv
    to: "on"
action:
  - service: media_player.select_source
    target:
      entity_id: media_player.owntone_server
    data:
      source: "Plattenspieler"
  - service: media_player.turn_on
    target:
      entity_id:
        - media_player.owntone_output_homepod_links
        - media_player.owntone_output_homepod_rechts
  - service: media_player.media_play
    target:
      entity_id: media_player.owntone_server
