alias: Plattenspieler OwnTone starten
mode: restart
trigger:
  - platform: state
    entity_id: binary_sensor.plattenspieler_aktiv
    to: "on"
action:
  - service: rest_command.owntone_outputs_wohnzimmer
  - delay: "00:00:01"
  - service: rest_command.owntone_play_plattenspieler
