alias: Plattenspieler OwnTone stoppen
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.plattenspieler_aktiv
    to: "off"
action:
  - service: rest_command.owntone_stop
  - delay: "00:00:01"
  - service: rest_command.owntone_outputs_off
