alias: Plattenspieler Stream starten
mode: restart
trigger:
  - platform: state
    entity_id: binary_sensor.plattenspieler_aktiv
    to: "on"
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.homepod
    data:
      media_content_id: "http://OMV-IP:8090/turntable.mp3"
      media_content_type: "music"
