mqtt:
  binary_sensor:
    - name: "Plattenspieler aktiv"
      unique_id: plattenspieler_aktiv
      state_topic: "home/turntable/state"
      availability_topic: "home/turntable/availability"
      payload_on: "ON"
      payload_off: "OFF"
      device_class: sound

turntable_media_source:
  name: "Plattenspieler"
  url: "http://192.168.178.203:8090/turntable.mp3"
  mime_type: "audio/mpeg"
